import { ReactNode } from "react"
import Header from "@/web/components/Header"
import Footer from "@/web/components/Footer"
import "./globals.css"
import StyledComponentsRegistry from "@/lib/AntdRegistry"
import { Inter } from "next/font/google"
import WebPrivateSession from "@/session/WebPrivateSession"
const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function Layout(props: Readonly<{ children?: ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${inter.className} m-0 flex flex-col`}>
        <StyledComponentsRegistry>
          <WebPrivateSession>
            <Header />
            <div className="overflow-hidden w-full">{props.children}</div>
            <Footer />
          </WebPrivateSession>
        </StyledComponentsRegistry>
      </body>
    </html>
  )
}
